### PR TITLE
docs: connect Python Translate client library to nebulous serverless example

### PR DESCRIPTION
**Pull request by wescpy**
Not adding new code but linking to another repo with a sample app using this API as another sample for users; added folder with README per @busunkim96

### CODE REVIEW

**Review by dandhlee — APPROVED** [review]
LGTM! I wonder if we can increase the visibility of this by adding it to the README on the top directory. Not sure if that's a client library style though 🤔

**Comment by wescpy** [comment]
@dandhlee Added a section at the bottom of the top-level `README`... PTAL when you get a chance. I'm done w/my updates, so feel free to submit or give me perms to merge the PR... thx & have a great wknd!

**Comment by dandhlee** [comment]
Have a good weekend! :D

I don't feel qualified enough to touch on a client library for common style, I'll wait for Bu Sun to chime in 😅

**Comment by wescpy** [comment]
NP Dan! Also added Eric (hi!) and Torry (hi to you too) as managers.

**Review by busunkim96 — APPROVED** [review]

**Review by telpirion — APPROVED** [review]

**Comment by wescpy** [comment]
Thx all. Can someone merge for me (or give me write perms to do so)?

**Comment by wescpy** [comment]
Thx for the merge @dandhlee (and everyone else for the LGTMs)!

**Pull request merged**
